version: "3"
services:
    nginx:
        build: ./nginx/
        ports:
            - 8000:80
        links:
            - php
        volumes_from:
            - app

    php:
        build: ./php/
        expose:
            - 9000
        volumes_from:
            - app

    app:
        image: php:7.0-fpm
        volumes:
            - ./www:/var/www/html
        command: "true"
